name: Portworx
description: |
  Volume plugin for Portworx Elastic Data Fabric, providing scale-out persistent storage for containers.
version: 1.2.12.1-OCI
category: Storage
labels:
  io.rancher.orchestration.supported: 'cattle'
