portworx:
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  image: portworx/oci-monitor:1.2.11.10
  container_name: px
  ipc: host
  net: host
  
  privileged: true
  environment:
    CLUSTER_ID: ${CLUSTER_ID}
    KVDB: ${KVDB}
    HDR_DIR: ${HEADER_DIR}
    USE_DISKS: ${USE_DISKS}
    ENABLE_ATTR_CACHE: true
  volumes:
     - /dev:/dev
     - ${HEADER_DIR}:${HEADER_DIR}
     - /etc/pwx:/etc/pwx
     - /var/cores:/var/cores
     - /opt/pwx:/opt/pwx
  command: entrypoint /runc-entry-point.sh --rm -i && /opt/pwx/bin/px-runc install -c ${CLUSTER_ID} -k ${KVDB} ${USE_DISKS}

